---
title: "Worked example: global Arabidopsis 1001G dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Worked example: global Arabidopsis 1001G dataset}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mar)
library(terra)
```

```{r core commands}
data(gm1001g)
obssfs <- sfs(gm1001g)
theorydf <- MARtheory(gm1001g)
mardf <- MARsampling(gm1001g, myseed = 91)
extdf <- MARextinction(gm1001g, myseed = 91)
marfit <- MARcalc(mardf)
```

```{r results}
# extract resolution
sm <- mar:::.get_samplemap(gm1001g$maps)
sm

# cell info
cellinfo <- as.vector(table(gm1001g$maps$cellid))
length(cellinfo)
summary(cellinfo)
```

```{r mar}
marfitsum <- summary(marfit)
round(marfitsum$Parameters['z',c('Estimate', '2.5%', '97.5%')], digits = 2)
round(marfitsum$Parameters['z', 'Pr(>|t|)'], digits = 3)
round(marfitsum$R2a, digits = 2)
```

```{r marasq}
marfit_asq <- MARcalc(mardf, Atype = 'Asq')
marfitsum <- summary(marfit_asq)
round(marfitsum$Parameters['z',c('Estimate', '2.5%', '97.5%')], digits = 2)
round(marfitsum$Parameters['z', 'Pr(>|t|)'], digits = 3)
round(marfitsum$R2a, digits = 2)
```

```{r extpred}
a = 0.38
z = 0.46
m_remaining = (1-a)^z
m_remaining
```

```{r marother}
extract_summary <- function(x) {
    sumx <- summary(x)
    a = round(sumx$Parameters['z',c('Estimate', '2.5%', '97.5%')], digits = 2)
    b = round(sumx$Parameters['z', 'Pr(>|t|)'], digits = 3)
    c = round(sumx$R2a, digits = 2)
    out <- c(a,b,c)
    return(out)
}
Mtypes = c('E', 'thetaw', 'thetapi')
marfit_list <- lapply(Mtypes, MARcalc, mardf = mardf)
summarydf <- do.call(rbind, lapply(marfit_list, extract_summary))
dimnames(summarydf)[[1]] <- Mtypes
dimnames(summarydf)[[2]][4:5] <- c('Pr(>|t|)', 'R2_adj')
print(summarydf)
```

```{r Fig2, eval = FALSE}
pdf(file = 'Fig2.pdf', width = 10, height = 8)
par(mfrow = c(2,2), mar = c(4,4,3,2))
plot(gm1001g$maps, xlab = "Easting (EPSG:8857)", ylab = "Northing", pax = list(cex.lab = 1))
mtext("A", side = 3, line = 1, adj = 0, cex = 1.4, font = 2)
plot(obssfs, expected = gm1001g, log = 'x')
mtext("B", side = 3, line = 1, adj = 0, cex = 1.4, font = 2)
plot(mardf, fit = marfit$par)
mtext("C", side = 3, line = 1, adj = 0, cex = 1.4, font = 2)
plot(extdf, fit = marfit$par)
mtext("D", side = 3, line = 1, adj = 0, cex = 1.4, font = 2)
dev.off()
```


```{r FigS1, eval = FALSE}
pdf(file = 'FigS1.pdf', width = 6, height = 5)
plot(mardf, fit = TRUE, Atype = 'N', theory = theorydf)
dev.off()
```



```{r FigS2, eval = FALSE}
pdf(file = 'FigS2.pdf', width = 6, height = 5)
plot(mardf, fit = TRUE, Atype = 'Asq')
dev.off()
```

```{r FigS3, eval = FALSE}
Mtypes = c('E', 'thetaw', 'thetapi')
pdf(file = 'FigS3.pdf', width = 5, height = 12)
par(mfrow = c(1,3))
for (Mtype in Mtypes) {
    mtext("A", side = 3, line = 1, adj = 0, cex = 1.4, font = 2)
    plot(mardf, fit = TRUE, Mtype = Mtype)
}
dev.off()
```

```{r FigS4, eval = FALSE}
pdf(file = 'FigS4.pdf', width = 6, height = 5)
plot(extdf, fit = TRUE)
curve((1 - x)^marfit$par['z'], add = TRUE, col = 'red')
dev.off()
```


